project:
  type: website

website:
  title: "Aquaakuma"
  navbar:
    title: false
    logo: images/home-1.svg
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Aquaakuma
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    html-math-method:
      method: katex